version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    image: nemanick/foodgram-backend
    restart: always
    ports:
      - "8080:8000"
      - "8080:8000/udp"
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    image: nemanick/foodgram-frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  static_value:
  media_value:
